## Mod Properties
mod_id=oddsandends
mod_name=Odds And Ends
repo_name=OddsAndEnds
mod_license=MIT
mod_version=3.0.0
mod_author=RedCraft86
mod_group_id=com.redcraft86.oddsandends
mod_description=An assortment of random tweaks and features added to Minecraft.
mod_credits=To anyone who may have contributed