## Dependencies
lanternlib_version_range=[2.3,2.4)

## Mod Properties
mod_id=oddsandends
mod_name=Odds And Ends
repo_name=OddsAndEnds
mod_license=MIT
mod_version=2.1.3
mod_author=RedCraft86
mod_group_id=com.redcraft86.oddsandends
mod_description=An assortment of random tweaks and features added to Minecraft.
mod_credits=To anyone who may have contributed