## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_version=2023.09.03

## Dependencies
lanternlib_version_range=[2.2.0]

## Mod Properties
mod_id=oddsandends
mod_name=Odds And Ends
repo_name=OddsAndEnds
mod_license=MIT
mod_version=2.0.6
mod_author=RedCraft86
mod_group_id=com.redcraft86.oddsandends
mod_description=An assortment of random tweaks and features added to Minecraft.
mod_credits=To anyone who may have contributed