modLoader="javafml"
license="${mod_license}"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/RedCraft86/${repo_name}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/RedCraft86/${repo_name}"
credits="${mod_credits}"
logoFile="logo.png"
#updateJSONURL=""

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="lanternlib"
type="required"
versionRange="[${lanternlib_version},)"
ordering="AFTER"
side="BOTH"

[modproperties.${mod_id}]
catalogueImageIcon="logo.png"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
